#!/usr/bin/env python3
"""Vendor the generic ``loop_runner`` package into a host repository.

The loop runner is project-agnostic and lives upstream in this repository. A host
consumes it as a *pinned, generated* copy — single source of truth, no hand-maintained
duplicate — recorded in a ``VENDOR.json`` manifest. ``--check`` fails on any drift.

Usage:
    python tools/vendor_loop_runner.py --to <host-dir>/loop_runner   # create
    python tools/vendor_loop_runner.py --check <host-dir>            # verify
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = "loop_runner"
SOURCE = ROOT / "skills" / "loop" / "scripts" / PACKAGE
MANIFEST = "VENDOR.json"
NOTICE = "VENDORED.md"
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo")


def _hashes(base: Path) -> dict[str, str]:
    files = sorted(p for p in base.rglob("*.py") if "__pycache__" not in p.parts)
    return {
        str(p.relative_to(base)).replace("\\", "/"): hashlib.sha256(
            p.read_bytes()
        ).hexdigest()
        for p in files
    }


def _notice() -> str:
    return (
        "<!-- generated by tools/vendor_loop_runner.py; DO NOT EDIT -->\n"
        "# Vendored: loop_runner\n\n"
        "Generated from `agentic-tools` `skills/loop/scripts/loop_runner`. Edit upstream,\n"
        "then re-vendor. `python tools/vendor_loop_runner.py --check <host-dir>` verifies it.\n"
    )


def vendor(target: Path) -> int:
    """Copy the package to ``target/loop_runner`` and write the manifest + notice."""
    package_dir = target / PACKAGE
    if package_dir.exists():
        raise ValueError(f"refusing to overwrite existing package: {package_dir}")
    target.mkdir(parents=True, exist_ok=True)
    shutil.copytree(SOURCE, package_dir, ignore=IGNORE)
    manifest = {
        "schema": "loop.vendor.v1",
        "source": "agentic-tools",
        "skill": "loop",
        "package": PACKAGE,
        "files": _hashes(package_dir),
    }
    (target / MANIFEST).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (target / NOTICE).write_text(_notice(), encoding="utf-8")
    print(f"Vendored {PACKAGE}: {len(manifest['files'])} files -> {package_dir}")
    return 0


def check(target: Path) -> int:
    """Fail if the vendored copy drifts from its manifest or from upstream."""
    manifest_path = target / MANIFEST
    if not manifest_path.is_file():
        print(f"Error: missing {manifest_path}", file=sys.stderr)
        return 1
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    actual = _hashes(target / PACKAGE)
    errors: list[str] = []
    if actual != manifest.get("files"):
        errors.append("vendored package drifts from its VENDOR.json manifest")
    upstream = _hashes(SOURCE)
    if actual != upstream:
        missing = sorted(set(upstream) - set(actual))
        extra = sorted(set(actual) - set(upstream))
        changed = sorted(
            k for k in set(actual) & set(upstream) if actual[k] != upstream[k]
        )
        errors.append(
            f"vendored package differs from upstream (missing={missing} extra={extra} changed={changed})"
        )
    if errors:
        for error in errors:
            print(f"Error: {error}", file=sys.stderr)
        return 1
    print(f"Vendored {PACKAGE} is current ({len(actual)} files)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--to", metavar="HOST_DIR", help="create the vendored package here"
    )
    group.add_argument("--check", metavar="HOST_DIR", help="verify a vendored package")
    args = parser.parse_args(argv)
    try:
        if args.to:
            return vendor(Path(args.to).resolve())
        return check(Path(args.check).resolve())
    except (OSError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
